export async function getServerSideProps({ res }) {
  const base = process.env.NEXT_PUBLIC_URL || 'https://horlurtestet.vercel.app';
  const pages = [{"path":"","priority":"1.0","changefreq":"daily"},{"path":"/om-oss","priority":"0.5","changefreq":"monthly"},{"path":"/kontakt","priority":"0.4","changefreq":"monthly"},{"path":"/integritetspolicy","priority":"0.3","changefreq":"yearly"},{"path":"/horlur","priority":"0.8","changefreq":"weekly"},{"path":"/laptop","priority":"0.8","changefreq":"weekly"},{"path":"/mobiltelefon","priority":"0.8","changefreq":"weekly"},{"path":"/surfplatta","priority":"0.8","changefreq":"weekly"},{"path":"/smartwatch","priority":"0.8","changefreq":"weekly"},{"path":"/jamfor/sony-wh-1000xm5-vs-bose-noise-cancelling-headphones-700","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/sony-wh-1000xm5-vs-apple-airpods-max","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/sony-wh-1000xm5-vs-sennheiser-momentum-4-wireless","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/sony-wh-1000xm5-vs-jabra-elite-85h","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/sony-wh-1000xm5-vs-bang-olufsen-beoplay-h95","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/sony-wh-1000xm5-vs-akg-n700nc-m2","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/bose-noise-cancelling-headphones-700-vs-apple-airpods-max","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/bose-noise-cancelling-headphones-700-vs-sennheiser-momentum-4-wireless","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/bose-noise-cancelling-headphones-700-vs-jabra-elite-85h","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/bose-noise-cancelling-headphones-700-vs-bang-olufsen-beoplay-h95","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/bose-noise-cancelling-headphones-700-vs-akg-n700nc-m2","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/apple-airpods-max-vs-sennheiser-momentum-4-wireless","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/apple-airpods-max-vs-jabra-elite-85h","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/apple-airpods-max-vs-bang-olufsen-beoplay-h95","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/apple-airpods-max-vs-akg-n700nc-m2","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/sennheiser-momentum-4-wireless-vs-jabra-elite-85h","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/sennheiser-momentum-4-wireless-vs-bang-olufsen-beoplay-h95","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/sennheiser-momentum-4-wireless-vs-akg-n700nc-m2","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/jabra-elite-85h-vs-bang-olufsen-beoplay-h95","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/jabra-elite-85h-vs-akg-n700nc-m2","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/bang-olufsen-beoplay-h95-vs-akg-n700nc-m2","priority":"0.7","changefreq":"weekly"}];
  const xml = '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' +
    pages.map(function(p) { return '<url><loc>'+base+p.path+'</loc><lastmod>2026-06-24</lastmod><changefreq>'+p.changefreq+'</changefreq><priority>'+p.priority+'</priority></url>'; }).join('') +
    '</urlset>';
  res.setHeader('Content-Type', 'application/xml');
  res.setHeader('Cache-Control', 's-maxage=86400, stale-while-revalidate');
  res.write(xml); res.end();
  return { props: {} };
}
export default function Sitemap() { return null; }