export async function getServerSideProps({ res }) {
  const base = process.env.NEXT_PUBLIC_URL || 'https://horlurtestet.vercel.app';
  const pages = [{"path":"","priority":"1.0","changefreq":"daily"},{"path":"/om-oss","priority":"0.5","changefreq":"monthly"},{"path":"/kontakt","priority":"0.4","changefreq":"monthly"},{"path":"/integritetspolicy","priority":"0.3","changefreq":"yearly"},{"path":"/horlur","priority":"0.8","changefreq":"weekly"},{"path":"/laptop","priority":"0.8","changefreq":"weekly"},{"path":"/mobiltelefon","priority":"0.8","changefreq":"weekly"},{"path":"/surfplatta","priority":"0.8","changefreq":"weekly"},{"path":"/smartwatch","priority":"0.8","changefreq":"weekly"},{"path":"/jamfor/sony-wh-1000xm5-vs-bose-quietcomfort-55","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/sony-wh-1000xm5-vs-apple-airpods-max-2","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/sony-wh-1000xm5-vs-sennheiser-momentum-5","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/sony-wh-1000xm5-vs-jabra-elite-100","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/sony-wh-1000xm5-vs-bowers-wilkins-px8","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/sony-wh-1000xm5-vs-bang-olufsen-beoplay-h10","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/bose-quietcomfort-55-vs-apple-airpods-max-2","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/bose-quietcomfort-55-vs-sennheiser-momentum-5","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/bose-quietcomfort-55-vs-jabra-elite-100","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/bose-quietcomfort-55-vs-bowers-wilkins-px8","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/bose-quietcomfort-55-vs-bang-olufsen-beoplay-h10","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/apple-airpods-max-2-vs-sennheiser-momentum-5","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/apple-airpods-max-2-vs-jabra-elite-100","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/apple-airpods-max-2-vs-bowers-wilkins-px8","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/apple-airpods-max-2-vs-bang-olufsen-beoplay-h10","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/sennheiser-momentum-5-vs-jabra-elite-100","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/sennheiser-momentum-5-vs-bowers-wilkins-px8","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/sennheiser-momentum-5-vs-bang-olufsen-beoplay-h10","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/jabra-elite-100-vs-bowers-wilkins-px8","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/jabra-elite-100-vs-bang-olufsen-beoplay-h10","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/bowers-wilkins-px8-vs-bang-olufsen-beoplay-h10","priority":"0.7","changefreq":"weekly"}];
  const xml = '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' +
    pages.map(function(p) { return '<url><loc>'+base+p.path+'</loc><lastmod>2026-06-24</lastmod><changefreq>'+p.changefreq+'</changefreq><priority>'+p.priority+'</priority></url>'; }).join('') +
    '</urlset>';
  res.setHeader('Content-Type', 'application/xml');
  res.setHeader('Cache-Control', 's-maxage=86400, stale-while-revalidate');
  res.write(xml); res.end();
  return { props: {} };
}
export default function Sitemap() { return null; }